language: rust
sudo: 

os:
  - linux
rust:
  - 1.5.0

install:
  - mkdir ./openssl
  - cd ./openssl
  - curl https://openssl.org/source/openssl-1.0.2e.tar.gz | tar --strip-components=1 -xzf -
  - ./config
  - make
  - sudo make install
  - cd ..

script:
  - cargo build

env:
  global:
    - BUILD_DIRECTORY=./target/debug/
    - secure: "APPf/DH4kQnqqD48hLVDzinhc/HTlnetra0muIz6xYfljc0VjXWSbd86zEm/IbQwjNJaD363wKhECNUFqJ4M9+8xj0Abwsb1LOuCWIu43+hJCwyPhz92BELNbrDpdfmz+asZVEcjKYCpoq7Bx58gnov8lZXZnCbR3QyOVKJcAN4k9McWN7uOycV2Ry2rdBgjaFBmdbPK3Eg6CyTq995DoIzBxhCBbY29AL1QVnCiw9phWMu1NP+dbjPXJyMfgHWIhJw/L7tS7DyrBIIkeNxIGbzg2kCKsBkHXfIG5oVvNNA093bfij4P48rdFQNExcP38LXFqYscIwGY3/VUxrATgY3amvOomLs5UNbtA8qCXytobBnF+9fV86WjFIN2S6qJ8Ya6QpMMhufaWuKHwaVy0y24Y4nAHSi2qIPl7SXvoSqR+eVR5U/m8WLfx9i50a0SLxVSHv9kbofVPR4E4bw679lgd7hsNTZW9w8Fj/vDKDqofQdYrjW8p86goodTIaut40+lUyNO6gXRJEN8vCST+aWmEKF8CbXZ16EtuRIn7lm3Sbyff1vtEJyidf3HCQ+Q8/30Gao4ESiOGX+EUILuIj4vGnpiWk4OD9bCJ44gFDCMvBF/LufW+3dTeWkYet55e8aVuM83ouPZOxqFrrZrWxQfrpm6SBdX2anb7aSAFJE="
    - secure: "EDMYqMKGj1vXxVJTD//1QMITMNeB8NIRL/xJJZo7hvPXABl/ho1Qm1c/9sny5nMc81Jw2SIu0+YBuhqKx3MhFPm3dlUlqXlo2qQ9B9PhKuR1ULqjtbvlcQ7vhoQL0t4KQcS8uVW5b2zlEeylLWDeda6Uki1D3Xxka06G1/LmaFUQlZpMNLVdrm73iUF/xo0Kmrd3MDXA0OhgeF7DkcowKlaz2yNgLdAMIK1Bx5d/worlSdD223QqSYpWHt8h7UZ3O3aSx3Xt9cgRB0O0wVta9QWKnxXVdzWEMTAQtJC0eBxolSdkARocuoegKlyvJ+Bc6o8SbQOnr6BHPWVYshmNqWM9TN7Dn4yHqRv267pTVLFDk3rQlmsG6BhnERmr8VUvfk7oZ8ZPBeHTnaNnm5GuxitOmQDMFuD6UFBE141pP62QA+9ErgrkzQGAYnfFVkR3brxI3PDBydUZYCVqWPKzsa1BFFttfnJiwKznjj5GpV5xGJciIAlFjZJYuDas/G65eqw/YoX34seAnwrkp26oWI8bNH8CGkcdX3mZ35FZ3iAxsrwZoQ6M/nYlqkM8KjO0QqSqf62wpGkGeA2a07xkhg1mZufC6cTv+0A8w8iOz+VQBCZXGjHHd48SDOaM/FwwIbnC3HEgQURV7axKlXF0jzYKA5vuxZQi6zR6SNjsrAw="
    - secure: "xa33PRm9NqFOFrAHVnt5LgW2HXJHdkv1ej4E2NBKjXLYbs8ZBcEkxH4zYgiB9UDl7B6BpEV9Jppy2lrMk4R9Cwu7P1JQ/O0pbrrxgtr+TsBXmbolroP+IAjd9Gkk0WY//wl+nkkYMOvEWOxx/5CumqNAigXXrCDTWnk6FL+abGudCp5tjkUwMLzh7RlponjM83lgTZm/vosahXbEIL3tCqGbnZmkIAk8mFCBBPWIHBC2TAVdq5C+DoccvUjeb3vzlMnCifoIaPM0tg1g9pBulT73uZQ+I85nzT3UTHwu7fKFvo01L1aA4xVzDI7AEywyHr9rEfg5CKcwHhyd/X7nnXKw9bb5t3RXT/cF3c4dDvYZu24yZOipM8TBoJjUGI9ZUjyR8S3GATh20uP+ef9h2u77GTeZGbsZe7sHd3kKtGVTGTsXcM12iPi9E5LdkqQfS9ukbrxsNv+oR+m83MIXcuP8iNQ8ct6W0UXzpLcf9kvNVvep6+9ojZv2UR4fsQQorohcnIFrWvcMDz1CTydC+J94cJbEKku/cyGRdvhsZahmckvUrC0EiZnBdXYzrpwYtXLTEQRR7zvyAUjDLlyR/UkIxjRqBzuTP27fOGHmrrf4ylY1mKcpIHd9oAXN7uXarjEBqQX7YipEAvhpMfkQJvcl0mNCSuy3B3p49hzw9Yw="
    - secure: "JiCw+z78OSCcnSqtVo+8PMJAfbDozKPPQXGBjmktBtlD0Vr7xoEC5RJfWgo/exFUFiZCYRpKaFMF9j9zp5xYNI+MSVowD9UjJHd4jNfpzcMQFvgVZ9ah6lxAdJpa8y6Iv/2ftoITVmgEpPC8Do41f+AqEypFik5/666+H1BhPzq81vhNQiBRZsgbEzqlTnrjPqYOXNokdTCrfSFjtMNrVjJiMG+e5EgbqUN2C/FtRqMNVw0KnzEFcyeRJ3GLzNHWx07SRa6cUVJOkfckpI66ls5SZvYjN/Yy4E1mEUaSf+0tUnCTFSHyret1ba1l+2h1mnJBwCljZ7o8HgUHqi58CrO1bEJJx3MWkKj17n0CuTGWQskom3AubUNrPe38n/O0X0ZulqJnVN6pr7SmUOHJuhFd23NnMfXGm9Eu9rThJwt5RjSBo69FfRDwakmk0xuSDjgwfg2E1jHZnjJMTistx/CsGQXU1MDGgjdGLTFlHfMuYvbDRWqmsVwHSd+Olo82x+LUUlLFqM8630JAuRZfNuqB8SukyxcOk5mSd+YzDkfWr2Gnfts76/Jb/F03Id80gND6peR8T2rbsNS7OgTkqzymShdKvp/WgGn9thJuVPHGuFf9i5vpHprYZcUyaZg/+92bJZHHcQJdEN+VXGlmoUiam78gAMb9Rh5sgP/KYZM="
    - secure: "ujDD48uHexMKM81fKyUpsmNiwkjtpAtYHWOfrqJpYJbGe8YxZSYvDLgwoz7g3bGC3z5GQglXZ+/0GS96d+mxmdCij/uned3z9fxmx/3pxbfX4imcxPhjSWfMqiKvu6HG2sckD/97r0SGtbbnCqa10oNWpMzTc9NooPTIdgH8PoEbVddO6h/AivJUAaFNFcUAlxga/rD/hED6D/KsJxq7wws62h/snrNXzH2wZwX8ScGZG+Eue+/Lkxb8mbNjwWZ3VzIwqa3ks5K9oa4TIIGbK9LUqJwX00VAEvda1xT2GygzVopODtvLEClXKBdjOJGst6GWyXSNPzVaxhcVFxwc5jrPzRv/TsOtt75KxP2thxyhd6Gvt/esILakZpmSgMvlgp4kEMVnGeC7KdOI8AuvEjRaDUc47wb4HZRjs/n2Vt6wLrlUO+BALQglsDSVdZu99VSbEAD9jfe3v9Dzfr9jLseJj1Rd/4kBAegdoniTRgIVQZqptTsCaTUVlXl+ZbegAmtCNSbBoKrxzBvq4XWSLYfjMAz52s0KYP9OoxYUxwgnOX5itrI+YkZdqWVgQHlaZ9IRNnhAc3BMmdm0loPqX1D1pjMibbCR72VG032r8eto8akx9WClAfK87a7fxVcfbs4qFyJrb4mE22dq69iYgQkO4E9aiafKn46IcE5Ho44="

after_success:
  - tar -zcf build.tar.gz ${BUILD_DIRECTORY}
  - buildLink=$(curl --upload-file ./build.tar.gz https://transfer.sh/build.tar.gz)
  - message="["${TRAVIS_BRANCH}"][Travis-CI]["${TRAVIS_OS_NAME}"]["${CXXCOMPILER}"]:%20#"${TRAVIS_BUILD_NUMBER}"%20PASSED"
  - data="name="${message}"&due=null&pos=top&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/ProjectUnknown/jobs/"${TRAVIS_JOB_ID}"&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
  - curl -s -o /dev/null -w "%{http_code}\\n" --data ${data} https://api.trello.com/1/cards;
  - echo $TRELLO_API_LIST_ID
  - echo $TRELLO_API_BUILD_PASS_ID
  - echo $TRELLO_API_TOKEN
  - echo $TRELLO_API_KEY
  - echo $BUILD_DIRECTORY

after_failure:
  - if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
         travis_branch="["${TRAVIS_BRANCH}"]"
      && ci_name="[Travis-CI]"
      && os_name="["${TRAVIS_OS_NAME}"]"
      && compiler="["${CXXCOMPILER}"]:"
      && fail="%20#"${TRAVIS_BUILD_NUMBER}"%20FAILED"
      && message=${travis_branch}${ci_name}${os_name}${compiler}${fail}
      && card_name="name="${message}"
      && additional_data="&due=null&pos=top"
      && description="&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/TrelloBST/jobs/"${TRAVIS_JOB_ID}"
      && trello_data="&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
      && data=${card_name}${additional_data}${description}${trello_data}
      && curl -s -o /dev/null -w "%{http_code}\n" --data ${data} https://api.trello.com/1/cards;
    fi
