language: rust
sudo: 

os:
  - linux
rust:
  - 1.5.0

install:
  - mkdir ./openssl
  - cd ./openssl
  - curl https://openssl.org/source/openssl-1.0.2e.tar.gz | tar --strip-components=1 -xzf -
  - ./config
  - make
  - sudo make install
  - cd ..

script:
  - cargo build

env:
  global:
    - BUILD_DIRECTORY=
    - secure: "IQW8f0eQz6UUH+5hqebxwEWRZj4KnL6J8HuZnlAtUKd6OE1LHpMAC7ARYVg/qcxr+Xc4KSnMkaUI62CHcGkM3Zl/boflrp9uUXN0hYL6z1dTNmcNYN04UKuTo524TmHoflfkO/ozpTMcq6oX+90nrvxhRYLTaL5wJvb5MNIc+xqKmlXGIP4FJ1kTf71QMP7+56gvhqymY8QOTHuDSuotjy9lEypfgrz5y1TKlYqR/qruj6VIVHbfAIA/S4JW7spdgYSsyaGVEv4SF2sa49jGE1Vx3uj6gRaBigAXFWoJVWx/C7uIAoxDnPgs6lN1BBwFFDMeN1x7fL4WbJJ4Ka2pD7pbR7GAf7mU7cAz2dd3T9Qbd6ZL0jBf/LOS3jET8zy0E5htiLwTfK/OpFjzSLXcx8FdJzxUc2ZihGig9GTlCksA/CFFvvGV6s+qcenin3UoSBZSiwECPdB2PLwtQR9vxooEGmgpSMiMFEoic3JsSr3kyyU2lnKdY7M2T3cGvxj9LsEZKXNXmTIIhWIe3QvpPy3/K9K6J7QFINpkbGcpkNPpDmvC4W7Fhumet78hdRXGh+z4eoEElpgKVGfHgHG5T2lDFGn6ElP3AIdcuLS9tIhiBWJBqTKwC3JRa1wCuHU+WMZngY0NN+ZB3SB70Oe3mY7NQWUrSVrXxC6QTH6WwjU="
    - secure: "mWrnT8yuoDwvAXxVMCDu3kLndOJRx8R+5ywm4ODMkKtSfCCWm3LVmVbCo7Iuvih0RJcMMzAnKvtaLE8uHT8V4+l1Vwgsg/Im3VBY2J5HKYQ21MjyjiW7VXnoXSQpoxP7+TLBs5MPx2EMvWRS7voahAF6FQ1C2pI4/YAc9qai3rsDlyRsaScXRNMS5FcgdENoIXaJzZoz2OAzUklQByGziWCKI1aYxE+ImaYFjbaa3077fpRU7gWfTMdqQweWJ6hDJGuz/F8c/1tkNQrmIJW21BmZSgPAlFxN9k9Wx/SchlJwSc4Ui7UZGQzlBXM7pLR5WmHP+AtPE7tAQYRC+43XWe/SH3Sc00cw8zvYX0UD1npNW2FM/eTkqkPWGvOhE8R6/hQAmcfXK4WJGqhvQ3c5EhVzE4yCG7qKHUzo4l3eItU9IkaB8t6JIoMA5LDiIGnzo6Wlcw0qRkbrgm2lFvnWy/GiA+P7iP3RxD7wvH86uEGtQLD/TFkOd/hzt3MDKPY7K92d5YYvCliqEy1UkmfrVOpTenA+2tywi1eEvHDR3G3fQi+gzP9YR2+XYa6ojXKl2je0+8ftNVDNn3+hHMCE41vxk84XwF5S8GdkD85PkkCQOwSn3y5ponIDvxkPNoQaNwHKhw9V4Xdn+L+bMYHO6J5V5BoeTZ7CkYpTrUCew2E="
    - secure: "HvECFbz0ROajJMDaKP2ccEqDZ/g16rLJHry/GgPThtdg6NAk3fGEeld68gNqmi6JgC/3I5u/VOA51o7gdl37/aLwgBMgmqcfbKtc4parJsoM9S+f1EFP4t/6P6jrcEFv51dcmJaEtsWCKf3ulUJaIt9GYuvbBn9sV45jDm8FytlunaA5BIv5yDqP3e1y364IsiPobRIJ5rjThO6gY0Ajw3lourc6uqu1u1/elNsQUxM2Z1pDF0DYqfjpe23p8Kv12VNF2gk8GepoMd7zpQDsLjB6/xXm9ijo4pJGNqQDdpNMJzGVD9yO8CzIGzTRoheCRbzAvEjk4KuY8Jt6nRjMRxSoUFJglqNvtrWqLDCo8zRCVX7ZWzv1bilheQMiFttDchKiWMA8pIHYR8g8hzjoA8AX/tssf5lAV5Fd9o+lpmC3787y2iYKtLpVI/A8THbOCzO6WZNe88q0X1HUOTLXVvxpF6eSkNTixFo5iLFIY8oVQES7q7+ZQEbJ0W781QFeEdaJqqyjRs353e+1rRd3FQsAMR4DsBbsFexG30dIkXkt7cg12D13Im7umHhK17nskseqgcz0KPO+j4UDELuVHuX5etfwt5SH+YxUS2ZrDMXrAlXUcf5fy2phkqimlCOGpxg12DugCXxMUbiIsEOueoRzMDU7iFEoTS6FhJukozk="
    - secure: "t80c9pRSppY4bnYAQW0gt/bfiyGdg8LDernPJkTvs7Unurg3hlfWG5DSQfH5OelfOsCIKnRgnJMnBMdFXNies2BCyIlQmxhuacPmovZrkxFBC/rYZaxtyxac8ySN5fmH6v6ua8MY9nqwYwCF8KNCA3/VIFE9wxt6FRfO7TrbL/bqCgWs8Jdjm+ZLjsrXCMitNaas5EGSN9gNKDryMV4+QIK7e40mPCnfJW3+PClm65hYdDqXsNlRgLfsLEPUW43a8Yhf+ka+ufHDUps66Sg5pR4h202MBZ3eZkoZkc2VaFeW2yMMoqV55i0nEPz/qg03VfiTFgqyNRrAkHGfd1kcahNp6QmsPXJjteSCRDOordv1aXWcIYKtNXh18HmgEBmo0RxsfHFThXfu94Veg5SpYdQu+XJMsMJ2zMg9lrXAOr1icoNLPcYFNDEWXxc7+tnI9YmJe+KI2fAclLhi22vOr7fdr4wxsY9rRp2ncXQqOF4hqOBZno5eIzoV9LP55VKMHLHK/ElGVkdwl96augzfdqakT8qkv97j1noyD9mbd8KUtgU3bo+mwf4KCn7pKv0uk2nxRefmDC3f1O3ablFMoJhRgcLCnFUBoD0Ol/843FCeq1DQTCiM34gBgxMSamVQfZu/ENpei40KTgBjm2umSuCw8K3eq1/w6qIn+7O32eI="
    - secure: "E/AFOu5464tnCX5mzkpUxOh3p2PuH3ZQuSp4npCBXUSVSiPmTTWZu2ldQIa2gaji2+oTTUWNEPuhMOKq/HmuENXArE695CvFkB9LiYFbPrgEtDc3LZxoOFBfm9P8ChYFvGtjXLErPSPnVzfMfsHJre6liCz82WBTQZ9aFm4rGHL8T8D4AL5NPnnpouYfWVgM0/7ug1yiTyAm7IyOFRzF1baOlM2uwfTCQzdVnZOE9swC3+siUsaqsog400yT19h3l5Kzh5b1rVjV+OIxgAfVlbqXPF9RX1VRNkHGJovVOiFbnYsvcBjSUcEOLiF87gSqYeYzbmjDj1nTEPVluNOLGbDvLf4ll6zkEK/nrYHBoXM4jH3DXOPAomfM0xyV6vGqJSjSixE2KE7DhqPU+G2ssHDKZYlzNPlzHjcVHONL96/WgFKh9KZbm2iKnn3XdS8QxycaTjNlUCLObzXS7X6iZw34dbCSc5WgHA8pjp84gxLmiE95sC2CqzGpLp6dRq4bLOd3IPppwbkSB0jXPHM7gy283tq2Z5FYlTuGaQffV2wZm69TxdyOzhHxKQpXUg7gUrOVmuR/EuE+TN8WQWpIfes2uGeuOuTIt4j82S1iTCwr6hNA27bpWAANyJXaQR8rcvHJLOysWBCqj4ApD2LaTPWvP8byiExlm4zf0Jr8E+g="

after_success:
  - if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
      && tar -zcf build.tar.gz ${BUILD_DIRECTORY}
      && buildLink=$(curl --upload-file ./build.tar.gz https://transfer.sh/build.tar.gz)
      && travis_branch="["${TRAVIS_BRANCH}"]
      && ci_name="[Travis-CI]"
      && os_name="["${TRAVIS_OS_NAME}"]"
      && compiler="["${CXXCOMPILER}"]:"
      && pass="%20#"${TRAVIS_BUILD_NUMBER}"%20PASSED"
      && message=${travis_branch}${ci_name}${os_name}${compiler}${pass}
      && card_name="name="${message}
      && additional_data="&due=null&pos=top"
      && description="&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/TrelloBST/jobs/"${TRAVIS_JOB_ID}
      && trello_data="&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
      && data=${card_name}${additional_data}${description}${trello_data}
      && curl -s -o /dev/null -w "%{http_code}\n" --data ${data} https://api.trello.com/1/cards;
    fi

after_failure:
  - if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
      && travis_branch="["${TRAVIS_BRANCH}"]
      && ci_name="[Travis-CI]"
      && os_name="["${TRAVIS_OS_NAME}"]"
      && compiler="["${CXXCOMPILER}"]:"
      && fail="%20#"${TRAVIS_BUILD_NUMBER}"%20FAILED"
      && message=${travis_branch}${ci_name}${os_name}${compiler}${fail}
      && card_name="name="${message}"
      && additional_data="&due=null&pos=top"
      && description="&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/TrelloBST/jobs/"${TRAVIS_JOB_ID}"
      && trello_data="&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
      && data=${card_name}${additional_data}${description}${trello_data}
      && curl -s -o /dev/null -w "%{http_code}\n" --data ${data} https://api.trello.com/1/cards;
    fi
