language: rust
sudo: required
os:
  - linux

rust:
  - 1.5.0

install:
  - mkdir ./openssl
  - cd ./openssl
  - curl https://openssl.org/source/openssl-1.0.2e.tar.gz | tar --strip-components=1 -xzf -
  - ./config
  - make
  - sudo make install
  - cd ..

script:
  - cargo build

env:
  global:
    - BUILD_DIRECTORY=./target/debug/
    - secure: "eDv0dAWzlnN7UxIE9wfmgtUwQv0uiCe9RFqvC0NHxOr/sD5wRm8pH+Q5aMHiUhmzvgSbfKy6crLPLTkfM/NMko8P6PQWTt+1/gDE7oS/cYCAdUWePjt/dWSpNptQjD63PD32JdJzMiYDMJHobT7qPnw+kGljTROfkGzUq+Ag12ETmBDo6tbYOsbwSj8q83yvD0N+UzeFNxTFrKfkG1IAkgtIdiX266kQOBHKsc9Df/YlFPGeNWDhEplmZIF5PDxAgr8xkANs+4M187+85SJ/5MeAPgPoyrRScvyitFIzvKh9UMDkWfdnOG4hZsTy+nanndKOGdvZFQX38lFuYQAUTUh4x7x6lSwcZWdKUcP256OT1hub5+5y56Gv2Ce43PMphukkzH5lHAFtYNbr2gN6TkoNW0HSPumYBw4Ogdf3MjvW8KD39GBdsx0E+CBzJctTGC0ec1tlxWnhcc4/e159aCPHKaSzXjve5BBTOSv8xhYt16pQpo+oOQ+Ga8/7c1eO3PqSAndkWcWBashtXAY3IdqvjgJta0TG/6q9tRMB9ll9TK88DnsOeYGFjxfl4DB3I8qvnukjMn67cwWaV98S2xW8BN/GZiDNkoHb4fgM1Cc7U8K2eR0TP9dSGYPtAHAkOaz1CD1k4g/ukBI5YmZJsY6lx+Qfy3OgGXXpvFl/WaY="
    - secure: "zYfJt//EcsSMVB0ukDDXLHmmLqtihN72jVzsZp6S2RzvDR8IxGe7Q3PMJtWg6hazI9i3BK7WRm3qeko+iDVzCP+VOo2Fmt96OeC1d6SkcrbD6KWVvxFjvIZj7sgentnzRwGCSvwFEFfQQ3g8iznWpOYD3OxODUTmEy47apqRtpHEAWs4Lt5/FIrQhurqjFl7qXlr054hcVMi6JDH0BKGrwZ3menucidtca8FYK8xUr3RwmUBEL6bIslGrshOvD80ZGcT7iHxDIccS/Z/AoWYp2Wym5bQDEeJTFck9eLpZyJytZyrKuOTnCKjkfaK1exzrmqgZNpuXjkju6dksb3fXVNn/BXsg3+9Y1W7VE+h0oNbzzkDl+ucQqXWbC+hGPYAOmnzgIohmbP3zQuTz0hNDyutDydI25GFEjaI8WpBP1rvwigRGAatRdYK0GpMuks/F5zhr277eb1BZoxd7EkEJ9QE6QRiCZaHSYu8oS4zywXQasT+L3lmZxVpJDf78PMgEgo6k+qLcQ0J2olz5jJKs/thLvfY4aOv+Mo1cEJGd12R4jXZBOlKYx9LtcB3P88AR5fPkUfbqLxh6Xd+T2kWAD4ehwehO9KtB20X+tKelIs9nK0O65anIdq7fExkrvb5Yh+8lvkgLG/1nTbbIbsvKa6BfLY+vPvrci2RyvRCEpA="
    - secure: "vzrGnbI1Na5jXGFwR9ix74Mf6EhL7/7+A2GBH0qesjO7iUiuDvcj412jK5moEThnXCsWb4lNPBj8HS5/OaLJE9ZCLhDVGumdeqMQlPUxmBvr0dIsOISnRkZKymaHGlSou8f7v7l+kmOlY0/9uqN41M3rJEDJCepbeqNE3sNbtMdf/QOJMqooWJcM/gW1yGXERG2Wnkpu9WR/uICjjrtILJwtGmasZwlzRvGvahBSelroq1pD46Axseb5f3B9YuFEUhm9zskmBp18C3eRpcPqIaOH/84ZPELS2hkWMCKkp115WlRxr1aqRBwN4jDc8WQghuwVYjFJPB4ImxsgGISazq8C8/5Xhc2KOZCAGaysdKxGW2DKUiMrSB4BYuqcTAY05GTRbBIOBPYatIsYMSXd354SlOTb14fBimizyAJRD39A28WSJQ8yWgYaGDD562/25uYR2+ngDSG9dwvlq2bAGeTYvZJLbkT2PqsnvyAIvoGKWKEvWM9MsCqIcGAioJXf8PmZZb2jYlv5zTmqzBQgDDQRgzSt0ek+dnCoLaYf71wSOzBI4SmSxoybgdEClm4nUG6J5Dxe4wiPFQz5V//BimtpwAF5M4uEMwnvmBlK/GV76io5UoUyMFkpYcAEq56JNNp0uJxz0fOLtcDskJbXAQY8AsHBUuUB+wdVIaZgIsI="
    - secure: "USx5Fi3fVwAPIAk2gfFqTdPbog5CqU24KEO7P2OufPH11tp+2xrmB+qRIN3VsYAd5VJd45uYNNwHBwtHWJZ6Rip3/+RR6xi0kVecBROh8BNi6fpnjuOE4axKsUWu+3Yk1q6h/9BLMNfszWRQYqczN/OE3eHzKt2i5gi45HSo6XTPkFWA/BA7JbIcXfdzmqd0C9k+ePrMM5oiDFgKvIKT3qZgPxCN5niyje2N5I8RoGXzgjm44+cMzewqoiK+fEWX0BRMr+dyf1MZv0YRvehELbrJMswqVEqtRMjhWhCbbpJWcD2VxyFUiHM6FE/CXiJ/fRFo/rRUZNh2Rx2QnZpwOjKyXrOemQZVGeY74ZfGYlrYEs6wvtcpKjXJyFXap/g00quu9FCMZE7muLURVWlytMn/C/j4WJ6gwWk0PVTK5NkhGevqIa49JAxAwUhxYxEDWryoJc88T7ZLwSjAy7Cvw83eVjMIpzjhtekBReZGowaDTR9OdfzRva7XKuGxy18sa25FRLJkIa3KVTsjM9KhEcxWtRpgLfuVAyEkWiwgXIxnVN21T6qFoT+OYlnRl2/6YTcwGPX6zKVDbw0ZGFgfXSFeYt27sQj4iadPMiPBES/FdwM1HkAnQlAmOQMsESKPbUlo+ZQ+Q/zBHxmOswKzweGXusI50+UCaVfIb+NorMs="
    - secure: "Sa3kbZcV3/EGtZd0+yBg8rzAApD5p6u9tIN3uz48nDf1cLEz6rpRSR2wtnGOIWkNQAYJLbUkcVWgo1igKMb5bz2xoI4xwrw+fYNr8QU3bHspCHpsnIvHk9jj84GtsIfSx/tib4GGcg0SYRxb7AgpGuqoaqPfuBkZMCW1c4tlfmXpqvE9OX76dqmhPDOU/uGkA3Xk7GgHQPH8kAyfGBHveU5+3D8U5l8frZq5Axxf/RS71PcqKbh6dQgr7Icylv4Xx6vKDOU+3BJvEVLaXj8wfFxm2oC2lBO8OcKvvMicbDqkDPpuC0yB8iQ9qlLxIan8SHPS17KZ5r6jxhU19aW0JeCqe41FOjOyAPEHvFd5V+JWrifJlOZaIKLjMHp4NiVeR5GEkAYSZdPYJj8Q4kOJqvd1RakaWznpCbG63T+yr43Ke+b0xnus9qpUTydq2q2sT/pEJ+lyybCtfYjYgR2dNqseEd7Ec3oXuOoLzsF0bOUbKKXqPcJyesG3lTnf2Jyta9maQ6qoLhEI+UxZhB13LxoIBkGx6COCsnDfGsPLwJh3UbSedBKlKTiwjxwx1cVGoxaHY0kBEkpgdicOLajVx7q2JYHr1qvRPD2mwWT+4cPOnf1ancs50r6jHOSKlVXvnuXxg8gZCF5r2qfMvzxqPrED4drwqQk4SZ8KZfVrvqE="

after_success:
  - if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
         tar -zcf build.tar.gz ${BUILD_DIRECTORY}
      && buildLink=$(curl --upload-file ./build.tar.gz https://transfer.sh/build.tar.gz)
      && travis_branch="["${TRAVIS_BRANCH}"]"
      && ci_name="[Travis-CI]"
      && os_name="["${TRAVIS_OS_NAME}"]"
      && compiler="[rustc "${TRAVIS_RUST_VERSION}"]:"
      && pass="%20#"${TRAVIS_BUILD_NUMBER}"%20PASSED"
      && message=${travis_branch}${ci_name}${os_name}${compiler}${pass}
      && card_name="name="${message}
      && additional_data="&due=null&pos=top"
      && description="&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/TrelloBST/jobs/"${TRAVIS_JOB_ID}
      && trello_data="&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key=0e190833c4db5fd7d3b0b26ae642d6fa"
      && data=${card_name}${additional_data}${description}${trello_data}
      && curl -s -o /dev/null -w "%{http_code}\n" --data ${data} https://api.trello.com/1/cards;
    fi

after_failure:
  - if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
         travis_branch="["${TRAVIS_BRANCH}"]"
      && ci_name="[Travis-CI]"
      && os_name="["${TRAVIS_OS_NAME}"]"
      && compiler="["${CXXCOMPILER}"]:"
      && fail="%20#"${TRAVIS_BUILD_NUMBER}"%20FAILED"
      && message=${travis_branch}${ci_name}${os_name}${compiler}${fail}
      && card_name="name="${message}"
      && additional_data="&due=null&pos=top"
      && description="&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/TrelloBST/jobs/"${TRAVIS_JOB_ID}"
      && trello_data="&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
      && data=${card_name}${additional_data}${description}${trello_data}
      && curl -s -o /dev/null -w "%{http_code}\n" --data ${data} https://api.trello.com/1/cards;
    fi
