language: rust
sudo: 

os:
  - linux
rust:
  - 1.5.0

install:
  - mkdir ./openssl
  - cd ./openssl
  - curl https://openssl.org/source/openssl-1.0.2e.tar.gz | tar --strip-components=1 -xzf -
  - ./config
  - make
  - sudo make install
  - cd ..

script:
  - cargo build

env:
  global:
    - BUILD_DIRECTORY=./target/debug/
    - secure: "kq0QV8vr2j+5vPb4ILuglyiEYnRAzzItAaFoKBy84Dye4jClx/xSYTqDYLVvK+N/S/Ha5I3fwh0QAtO08HQBfARRox1HgkBHvIGVhD37zvWxvLY3AwhRU1nFMNSf8jowpeNRmbB7VoZQTk26j77qGMJR/xb5tBi8khpWV71gs+NUWM5vhLW9ROA+v/uk19915vR+pcEzEUM5Ai3aKquDdZfwdNDp6v9ZhVwh2qVbZpL+N9WOSEyTMfGUNcZyw64JI1EaFxQDTpLrDGKhJfAcGcEST7yc+vrHNJzUZrHn+HrJzUbdV9RMv8xurwLzZarxXQT4P3vua0tr/RN+1eBIENNpuvbsVXlF1htYgbrl7qZrVDgUIAEduWFTLgRhY0gQTMD013eD+PEC8aH+U0hgxWXQ+2zuHK+/Prk0QmlpaTzkRqN91qjHwaOeqDOVDjlPecKjVpbX9nqyNN02dFieTJoF/3m4Z8zoTGgESOerfIQnpKZpP0eyWwWpYKvG+4AiEg2xGME0ZWr7tjTAkcqjI5upS158ldkHZ/stwvPgCh5S89IH6T+WRtjCSXk4cSjA0ob4EAzyB2/s1FHxhsHpCttV6jy5MHFRq+BqoAoUP3TQ3KtVB2SJc+MtQM7/L01P1NRyFmwMOQ7uDlH6Tbvw7JmGa57ZtJuWG6JZZDGEa1A="
    - secure: "hPWrIiL7l1GiXEkbXw6aW4k69pRUfK4jV61mL048D+HL4N5iZQ0Pdc/c6u12QXnEknlWnlJ44TvH8sL/Fk3xWGP+4HikWoVchyRzjXYC9Wt6IHDGMte9yoH3ypNp71MMa9kJ0cYtyZWwosXK18FG5D4wFtZgmhnukqQDFWLgbUJFRPgI315kn4Xk5U9YXEgLS8WhVL3YHIoTsUBfvcCIIfDR2vxGH9mZ0CSDldOdj90C5hBhDXTiz32Qzow8la9uad5ieDCyXCGZmLS9ZvEWu5Av/YfN96S278tlYh52lTtWDFybk5J95SW2TxEvuu+GqQVHtZhEdCkTmEwcY1z6i+PGjzliiriOrAZM0B49hMU107u+D11kpEPkcbwW1szjD0iq9hjbIP6n2MgfI+abpIDJNnszp2frSPh59CpHGMf4caMf0SIK93CNqtcvFlP8nWKooMWKRX3cEIMh2p/u8dC1W/dP03cSccbqO9nrPS9qtSPuhGhUUWMEz8nIlw+W0j0iV6Q7ZZRVO4fzDRbxLG0IIkB4skhpvV4TQuYY7EO8gmZ/AjpWFeXUe6LSO4RPArd7TmnE08lDtK7EL0SCX14v4BIf14oMcb9oxqmRyTadU1ZkMCMTAykcoiUuDxeVIvrhH4XAq9+AJnYW+lYID5tyiE3CVAdi0+Hc2oTYBDo="
    - secure: "pmWNU63CYSgmS7qGKvAJ8crG7VxDTwrHwj67Zwu2q8t/xdEZN5hCI4DXWU9TabjG0V5m0nkEPreSGnTuuw+OrG6mWv0VMUJTZXaZ67KoWJIZKoPYVIqI+cQaANpLyDkI2eCEuLr+iXycvsLz2uVLlCUKpmJN/jcM2LottemTuYSqKC+L5mXtLALws+T1NKT9OdQC8cCHfiULtCnFp6eJtz30QAQVlPQCnZk/DxOL6r8kFnEib6UXy0EZERALyWggzabfjPJrDmUMOrn5G9XAaM3868suE/gWOTLyFAq8d9c6Zz/TdSywqPpCUer5qpkHQR+zq5UJo4tRjo1DYzm16bc/GhBV7JhfEsAPpZKaY8rnfIg8lytSsLvhAwnPSnnmUSxIDpSYwKUSxAkAE14pudFAV7bOOhQ8Mvez88avQCZ5b0K9lw2wlPWDQgxWShIIHNu0dqZW2b8mvQh25eGYCTuwkhqBF34jxsnHSEiq6yF3/DdZzYyvHsmc0UpD9cE+/wMb0ePjg+R1qbLvFW/rL9QfBu86WrsZzYJIpkN6OxxWoeUPlk0rfouOJXVFfIytL3wH7zlSxwTcLajfhdh7j0hFKLxp//LbHiHHFSfaMqwsV8Rz9X7AuFTovBYjMdGHiy2tkjY+qQncbS4ytCvW5MYMWqAzR4c5QA0KzIyRgHE="
    - secure: "p4ldE/b1ki7fqjp1bf+qtTRNxurnPnwRsQObZFdh0jjsMmbWCnARBziMmARo3h72AQCyIYG9eFrqG83yd+8N6v2bZzyHS41BsKXlKDp4sqH7iYUAU6lsOL94N05rjMYCZ7fKx7+/sYqomXUu1zOTP/SSy5FBHxUEGS4TsToDZsbZ8IBazFSWaLasbGu4hpfwyxSqAGHq+N4dWYGHaFzJqqU8Mt14LTJFnHnjfSnuIGwhnUrJnwwP76N16ujhsFNP1unj2SN+q4wEpM8HdZT2EL//RHYa5+BkKOwdPEOpvn4QryrScujocECPJTXqFPihI6jv7ezkgX7FFjs95f9wW7ogZ3ny8K8PS3g0vyrKj1B5eksgwMxJPiAuFXfe1sXHzSk9t8U3kGUdSr0cYumrhC/nCjt2Pobjjn+BOnbzEYvUHpK3waR7niKptrQemIIB7iCNAVAQsDTwdG+z2hBGSmbmeh4KtRMyWUTFiJdxOe5fruAFLdbhIEMdSHIuQQTMmN5mIpbKoCqd2Q67/pXVEqOgLzjUfuzrkptzVlIPeKnLU0OeDaQgKsNr0G7WTO7w7k26Pt/yq6M+04gA5OVBVJLlCaiot0GqaszaoHg1ykoNXW4Ibkl7ssorm2gcX3JYRoXp6Smjz1AZuWfexMHhNhjvJndHhYX7bDNtrgIoaYY="
    - secure: "vJPpHnpkqcuKKZUIQ3exCJp7XBWimddq9XeqPsWkHGpnnl4MbX7T23gqi+9b7LzmNW5VOS0KT8boYukC5mxiUaKqjTPF2sihrNUXO9xXqupV5IetbYgkluFoJXZjvh4XbQNs4YyDEkSKF4GiHrMcqtU9AHfg71qlFOdydeLDX4sXNGPvjYFU3PXpz7WIz0hJ88p8y8T7vuI1blDOZnSUz2PW3xlogDmr8JXA+txRv/2/eG0TgSDKftKE8BiYPf4YfmrbOWnqT1apxcu4MeN5mSHHkH+L4406sOBXmyOm95p8fydkBk5xK1xcsI4GCBx1vPajdpIG+zM2ufIYFe5CzABgFJYS8qp65qyIRaXVhNriA/4g/JvoyhJrN3sVDD483KQ1BO/QgWjXImnij3uLY2zV5cfMbAeofH/hzFi2Q5ejKniUO0cyt1IkZFIXJ+fnTpmI5fq1KrN1V/yxIVBsZYk3rCVVHYJn3E+zD7dZSbnDmINJTJbv7oOY5ucaeKDILMcUUpb87cIWITC0ezGket5I2Pn4JbLwkrgIA6TI2RdVuGMhQGHtjvIbPQvqstnijyqZIKXxc7T0GvwUXX6zbrFiKKTY1HpeZ2n0Xkf9qzpO7lo+w89+EWB4jcTIK4qYtFvNIsmfmvIqFpK1vita3oNUgKXznwsjPF+nXPHFD6I="

after_success:
  - tar -zcf build.tar.gz ${BUILD_DIRECTORY}
  - buildLink=$(curl --upload-file ./build.tar.gz https://transfer.sh/build.tar.gz)
  - message="["${TRAVIS_BRANCH}"][Travis-CI]["${TRAVIS_OS_NAME}"]["${CXXCOMPILER}"]:%20#"${TRAVIS_BUILD_NUMBER}"%20PASSED"
  - data="name="${message}"&due=null&pos=top&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/ProjectUnknown/jobs/"${TRAVIS_JOB_ID}"&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
  - curl -s -o /dev/null -w "%{http_code}\\n" --data ${data} https://api.trello.com/1/cards;
  - echo $TRELLO_API_LIST_ID
  - echo $TRELLO_API_BUILD_PASS_ID
  - echo $TRELLO_API_TOKEN
  - echo $TRELLO_API_KEY
  - echo $BUILD_DIRECTORY

after_failure:
  - if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
         travis_branch="["${TRAVIS_BRANCH}"]"
      && ci_name="[Travis-CI]"
      && os_name="["${TRAVIS_OS_NAME}"]"
      && compiler="["${CXXCOMPILER}"]:"
      && fail="%20#"${TRAVIS_BUILD_NUMBER}"%20FAILED"
      && message=${travis_branch}${ci_name}${os_name}${compiler}${fail}
      && card_name="name="${message}"
      && additional_data="&due=null&pos=top"
      && description="&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/TrelloBST/jobs/"${TRAVIS_JOB_ID}"
      && trello_data="&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
      && data=${card_name}${additional_data}${description}${trello_data}
      && curl -s -o /dev/null -w "%{http_code}\n" --data ${data} https://api.trello.com/1/cards;
    fi
