language: rust
sudo: 

os:
  - linux
rust:
  - 1.5.0

install:
  - mkdir ./openssl
  - cd ./openssl
  - curl https://openssl.org/source/openssl-1.0.2e.tar.gz | tar --strip-components=1 -xzf -
  - ./config
  - make
  - sudo make install
  - cd ..

script:
  - cargo build

env:
  global:
    - BUILD_DIRECTORY=./target/debug/
    - secure: "cgoe3ZZ4wri0lvTxrRDjiD4h4fsfYdyRcMzgEfYU7GwFZsRRwrOAu5gARs9c0TXoItdW7RF4Pn0lVS8A8sO1Ed/Wq8ztAjzANJUx/CRRw1klmVj6uMe76Xw1hbgAt8LaEyj7BUdHw/fcfK0jzy9nVgAyJVtk5VxjgZTmI14MbfU="
    - secure: "nbSVAdANRN97PsjH3Yfzexh/1dWVF7u3Un5pY+twN7hkculea4tFd0UMxUSUDWkv1WGw57HLgpPM+YQkX/7DdneVjlLyMh5k6Atgiscrdw/BtJkXSPNqmXdd2MG9KvSLTLqdyhWIRKNvA8+lodTYPN0YKScuIlUXVs7SfdzCR8Y="
    - secure: "bJuIHjcrR0UgJb4h+mEuO0mtKHb2OqFuwyVvNcm41lP6WeHBlEWWbP0qkYEIAj6FZYW1pPOmiSSy/UgTfDv5eCMhG6M7YM/i9dkTjpBHbks5bbqqO8N3wPp3YVOiEIBrvStmXGLffzIb3aCc8NVdzo5T1g93vkveL43grB4LKnU="
    - secure: "FjMJnLhKgaUF3olc7382VknGuBlGbR1w/9U1lsZ73v1TG86/nKgoBAA6GcRl/NR+MGtwYt1Zknn+EOeZyrpITaAOBoEtVqLrZQdbVTYplldRWqSG/kpCtxELnBE84hcsVE8VVfWWQHL/WqRMwQkgakreiRCejpB5UEMPUuY9RNw="
    - secure: "QNEt8GmGyVukMuf2wVhHXQMlOQxsb5HFGoIiejlJ7/IrFH/fUbhg/g4tKC4JyncyVc4mJJ8BtxKZrp6m6Ny/8n8+W5wHw9w2aJZJrNBlzCyRQ7pmBQz6YvcRWpoRpr8TQtaZfIJNxWl8KH82vGEbJ4DFgwPeqxUatAKTl94adH0="

after_success:
  - tar -zcf build.tar.gz ${BUILD_DIRECTORY}
  - buildLink=$(curl --upload-file ./build.tar.gz https://transfer.sh/build.tar.gz)
  - message="["${TRAVIS_BRANCH}"][Travis-CI]["${TRAVIS_OS_NAME}"]["${CXXCOMPILER}"]:%20#"${TRAVIS_BUILD_NUMBER}"%20PASSED"
  - data="name="${message}"&due=null&pos=top&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/ProjectUnknown/jobs/"${TRAVIS_JOB_ID}"&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
  - curl -s -o /dev/null -w "%{http_code}\\n" --data ${data} https://api.trello.com/1/cards;
  - echo $TRELLO_API_LIST_ID
  - echo $TRELLO_API_BUILD_PASS_ID
  - echo $TRELLO_API_TOKEN
  - echo $TRELLO_API_KEY
  - echo $BUILD_DIRECTORY

after_failure:
  - if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
         travis_branch="["${TRAVIS_BRANCH}"]"
      && ci_name="[Travis-CI]"
      && os_name="["${TRAVIS_OS_NAME}"]"
      && compiler="["${CXXCOMPILER}"]:"
      && fail="%20#"${TRAVIS_BUILD_NUMBER}"%20FAILED"
      && message=${travis_branch}${ci_name}${os_name}${compiler}${fail}
      && card_name="name="${message}"
      && additional_data="&due=null&pos=top"
      && description="&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/TrelloBST/jobs/"${TRAVIS_JOB_ID}"
      && trello_data="&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
      && data=${card_name}${additional_data}${description}${trello_data}
      && curl -s -o /dev/null -w "%{http_code}\n" --data ${data} https://api.trello.com/1/cards;
    fi
