language: rust
sudo: 

os:
  - linux
rust:
  - 1.5.0

install:
  - mkdir ./openssl
  - cd ./openssl
  - curl https://openssl.org/source/openssl-1.0.2e.tar.gz | tar --strip-components=1 -xzf -
  - ./config
  - make
  - sudo make install
  - cd ..

script:
  - cargo build

env:
  global:
    - BUILD_DIRECTORY=./target/debug/
    - secure: "Ep3i+3J09WrsNcjX8LoeQm9tlShCSnrb6X32zg5Jm8uvcyD0ifgtCKUe2fft7692+/QVJrAh2YJustN3jKNitDNjFAUCi/bUFUVBcWII6kpS8GsXJRSeDodURX/EZOtwb0YnwB5cksSR7GZMyvnJ7IYQRmwAaiojDry5Q3rBhz04nDvpSpkbeFhf85Mtv9ItbT1/xEqbIu4avEKJo/Owu8Nd1+JrRD0T2js5UCBH3Q5R0Z/0Klbw6s/Cb/zWCy8oScEcp4L31KjyoICMU2FssJSMstoMnGt5NULSojxb9XuL/eiJnxnX+0NOV8bgyfXsAn0HWden794k7l2hBPXvHGI0ZgQltxyF28xP6SSBdLGFN+3FIsV4OxlnTNjl4W3ANcFu8rL+HMqlBT9MwU81aIAizof5e2jMh+EStxu3pJqpAd7BsvNIPZ41fUCjuKDQKAMbWB5ttoFAFg6ad52y3GA4lNsOxfJc8WFbMCBByx1lWovtchrcRndJqCUCqm5r62F7qBqCycvN2OVIseJlfbhe5XbD8oOz7hu7Rvw83stAVcbYD4YAZYmLnHOlBSX7IihVW24WVhvWjY8dzoXF8sGnwVKIkScQFi2VXFu1x732jctJb5aasjdiCDylIZemI0vAVsTG8/2S5Pt+VnAfEcAy0qtvLqZdCXiKkHk/FTQ="
    - secure: "T9iyl9teiG2D2VPNgHUPw6jvIKEZZQuUgQAfl6tlk27GNXnMEXALyBLhIohXa36lYZHAp9hxF7qyg1AW6DTg+QPH+TaAjw4rxYavmuXZNIQg872iPLNiiCDXdHJuDQjEYCEaoo2PWgKiV0Yqkg4CXdTqahJ5woTZiH1+eyyNRCshkH1oF0vY1CK35K12MGMz58a5yStfqHDmiZ4EwY06UZUQ+9MSIKsJaeNWcMTmWIKU5BZOGTx1MgZpPw+4osJ7T+4jKt7Mz8PwlyN4PFV0eSvJHLNMTeGhc6EheG6UCASBKFXklKxDnPNuwnTPv829G0mlpnn6MdLEuonwPxOM0NttOe1eme0FNU39FkdVNpdEMmcAxX/Qo/qMctcHuuxdUlAAQA+d8n+9B8Zd20ZHjbazhqnngGexwkKIeE3off0dPVr+XYGJRcTTdvYEJXXBF9zHLz7ZQdb9Rbx5CEQiJ8y6GZAb3rJyA23BZ7nrpk15h6AY1ky8Om2xybAcjyHYEKM51yTZ20AwGc9vuwoIxaPNsClGGcGfGNb2Z2xv7uEdrBpgjQwMJClI9139iz9cfXuJNnISHgs4Cj5cMUiD41MYd8AwLw86hiFACBnDnzQF2n4VC5ctRuK+yS9olnt9Z0LxhDow6MfyM1d+04AY4BHlQlCOasVFZ7ZoTEoNTn0="
    - secure: "xa33PRm9NqFOFrAHVnt5LgW2HXJHdkv1ej4E2NBKjXLYbs8ZBcEkxH4zYgiB9UDl7B6BpEV9Jppy2lrMk4R9Cwu7P1JQ/O0pbrrxgtr+TsBXmbolroP+IAjd9Gkk0WY//wl+nkkYMOvEWOxx/5CumqNAigXXrCDTWnk6FL+abGudCp5tjkUwMLzh7RlponjM83lgTZm/vosahXbEIL3tCqGbnZmkIAk8mFCBBPWIHBC2TAVdq5C+DoccvUjeb3vzlMnCifoIaPM0tg1g9pBulT73uZQ+I85nzT3UTHwu7fKFvo01L1aA4xVzDI7AEywyHr9rEfg5CKcwHhyd/X7nnXKw9bb5t3RXT/cF3c4dDvYZu24yZOipM8TBoJjUGI9ZUjyR8S3GATh20uP+ef9h2u77GTeZGbsZe7sHd3kKtGVTGTsXcM12iPi9E5LdkqQfS9ukbrxsNv+oR+m83MIXcuP8iNQ8ct6W0UXzpLcf9kvNVvep6+9ojZv2UR4fsQQorohcnIFrWvcMDz1CTydC+J94cJbEKku/cyGRdvhsZahmckvUrC0EiZnBdXYzrpwYtXLTEQRR7zvyAUjDLlyR/UkIxjRqBzuTP27fOGHmrrf4ylY1mKcpIHd9oAXN7uXarjEBqQX7YipEAvhpMfkQJvcl0mNCSuy3B3p49hzw9Yw="
    - secure: "JiCw+z78OSCcnSqtVo+8PMJAfbDozKPPQXGBjmktBtlD0Vr7xoEC5RJfWgo/exFUFiZCYRpKaFMF9j9zp5xYNI+MSVowD9UjJHd4jNfpzcMQFvgVZ9ah6lxAdJpa8y6Iv/2ftoITVmgEpPC8Do41f+AqEypFik5/666+H1BhPzq81vhNQiBRZsgbEzqlTnrjPqYOXNokdTCrfSFjtMNrVjJiMG+e5EgbqUN2C/FtRqMNVw0KnzEFcyeRJ3GLzNHWx07SRa6cUVJOkfckpI66ls5SZvYjN/Yy4E1mEUaSf+0tUnCTFSHyret1ba1l+2h1mnJBwCljZ7o8HgUHqi58CrO1bEJJx3MWkKj17n0CuTGWQskom3AubUNrPe38n/O0X0ZulqJnVN6pr7SmUOHJuhFd23NnMfXGm9Eu9rThJwt5RjSBo69FfRDwakmk0xuSDjgwfg2E1jHZnjJMTistx/CsGQXU1MDGgjdGLTFlHfMuYvbDRWqmsVwHSd+Olo82x+LUUlLFqM8630JAuRZfNuqB8SukyxcOk5mSd+YzDkfWr2Gnfts76/Jb/F03Id80gND6peR8T2rbsNS7OgTkqzymShdKvp/WgGn9thJuVPHGuFf9i5vpHprYZcUyaZg/+92bJZHHcQJdEN+VXGlmoUiam78gAMb9Rh5sgP/KYZM="
    - secure: "ujDD48uHexMKM81fKyUpsmNiwkjtpAtYHWOfrqJpYJbGe8YxZSYvDLgwoz7g3bGC3z5GQglXZ+/0GS96d+mxmdCij/uned3z9fxmx/3pxbfX4imcxPhjSWfMqiKvu6HG2sckD/97r0SGtbbnCqa10oNWpMzTc9NooPTIdgH8PoEbVddO6h/AivJUAaFNFcUAlxga/rD/hED6D/KsJxq7wws62h/snrNXzH2wZwX8ScGZG+Eue+/Lkxb8mbNjwWZ3VzIwqa3ks5K9oa4TIIGbK9LUqJwX00VAEvda1xT2GygzVopODtvLEClXKBdjOJGst6GWyXSNPzVaxhcVFxwc5jrPzRv/TsOtt75KxP2thxyhd6Gvt/esILakZpmSgMvlgp4kEMVnGeC7KdOI8AuvEjRaDUc47wb4HZRjs/n2Vt6wLrlUO+BALQglsDSVdZu99VSbEAD9jfe3v9Dzfr9jLseJj1Rd/4kBAegdoniTRgIVQZqptTsCaTUVlXl+ZbegAmtCNSbBoKrxzBvq4XWSLYfjMAz52s0KYP9OoxYUxwgnOX5itrI+YkZdqWVgQHlaZ9IRNnhAc3BMmdm0loPqX1D1pjMibbCR72VG032r8eto8akx9WClAfK87a7fxVcfbs4qFyJrb4mE22dq69iYgQkO4E9aiafKn46IcE5Ho44="

after_success:
  - tar -zcf build.tar.gz ${BUILD_DIRECTORY}
  - buildLink=$(curl --upload-file ./build.tar.gz https://transfer.sh/build.tar.gz)
  - message="["${TRAVIS_BRANCH}"][Travis-CI]["${TRAVIS_OS_NAME}"]["${CXXCOMPILER}"]:%20#"${TRAVIS_BUILD_NUMBER}"%20PASSED"
  - data="name="${message}"&due=null&pos=top&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/ProjectUnknown/jobs/"${TRAVIS_JOB_ID}"&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
  - curl -s -o /dev/null -w "%{http_code}\\n" --data ${data} https://api.trello.com/1/cards;
  - echo $TRELLO_API_LIST_ID
  - echo $TRELLO_API_BUILD_PASS_ID
  - echo $TRELLO_API_TOKEN
  - echo $TRELLO_API_KEY
  - echo $BUILD_DIRECTORY

after_failure:
  - if [ ${TRAVIS_SECURE_ENV_VARS} = true ] ; then
         travis_branch="["${TRAVIS_BRANCH}"]"
      && ci_name="[Travis-CI]"
      && os_name="["${TRAVIS_OS_NAME}"]"
      && compiler="["${CXXCOMPILER}"]:"
      && fail="%20#"${TRAVIS_BUILD_NUMBER}"%20FAILED"
      && message=${travis_branch}${ci_name}${os_name}${compiler}${fail}
      && card_name="name="${message}"
      && additional_data="&due=null&pos=top"
      && description="&desc=\[Build\]:%20"${buildLink}"%0D\[Logs\]:%20https://travis-ci.org/Cyberunner23/TrelloBST/jobs/"${TRAVIS_JOB_ID}"
      && trello_data="&idList="${TRELLO_API_LIST_ID}"&idLabels="${TRELLO_API_BUILD_PASS_ID}"&token="${TRELLO_API_TOKEN}"&key="${TRELLO_API_KEY}
      && data=${card_name}${additional_data}${description}${trello_data}
      && curl -s -o /dev/null -w "%{http_code}\n" --data ${data} https://api.trello.com/1/cards;
    fi
