os: Visual Studio 2015

environment:
  TRELLO_API_KEY: 0e190833c4db5fd7d3b0b26ae642d6fa
  TRELLO_APP_TOKEN:
    secure: 2BDZzUNMc1ganOBx/wtVo6OacN3hdo972bsRl6RwHaGHD50QtxkLOosT/bjNl3S1gSpPg0AQjCZxHSnMr3vJRQNh9p1z2BkWQO31CrWZrWk=
  TRELLO_API_LIST_ID:
    secure: 1J6YqnRnhPRg9ke5Si2ga7sWzVGtmSCGXSr5rqswl4s=
  TRELLO_API_BUILD_PASS_ID:
    secure: 8tnvk1xusIDSQ1l+pjLs0mgC8OVbIvkDCM9G4kdj8Go=
  TRELLO_API_BUILD_FAIL_ID:
    secure: oNcqUlgc1aEjPA9npRLtr0aUJK0yyzjWIzqdxaQeF+A=

build_script:
  - ps: |
      $appveyor_branch = "[$($env:APPVEYOR_REPO_BRANCH)]"
      $ci_name         = "[AppVeyor]"
      $os_name         = "[Windows]"
      $compiler        = "[$($env:COMPILER)]:%20"
      $pass            = "#$($env:APPVEYOR_BUILD_NUMBER)%20FAILED"
      $card_name       = "name=$($appveyor_branch)$($ci_name)$($os_name)$(compiler)$(pass)"
      $additional_data = "&due=null&pos=top"
      $description     = "&desc=\[Logs\]:%20https://ci.appveyor.com/project/$($env:APPVEYOR_REPO_NAME)/build/$($env:APPVEYOR_BUILD_VERSION)/job/$($env:APPVEYOR_JOB_ID)
      $trello_data     = "&idList=$($env:TRELLO_API_LIST_ID)&idLabels=$($env:TRELLO_API_BUILD_PASS_ID)&token=$($env:TRELLO_APP_TOKEN)&key=$($env:TRELLO_API_KEY)"
      $data            = "$($card_name)$($additional_data)$($description)$($trello_data)"
      Write-Host $($data)
      curl -s --data $($data) https://api.trello.com/1/cards

