
os: Visual Studio 2015

environment:
  BUILD_DIRECTORY: ./target
  COMPILER: MSVC
  TRELLO_API_KEY: 0e190833c4db5fd7d3b0b26ae642d6fa
  TRELLO_APP_TOKEN:
    secure: 2BDZzUNMc1ganOBx/wtVo6OacN3hdo972bsRl6RwHaGHD50QtxkLOosT/bjNl3S1gSpPg0AQjCZxHSnMr3vJRQNh9p1z2BkWQO31CrWZrWk=
  TRELLO_API_LIST_ID:
    secure: 1J6YqnRnhPRg9ke5Si2ga7sWzVGtmSCGXSr5rqswl4s=
  TRELLO_API_BUILD_PASS_ID:
    secure: 8tnvk1xusIDSQ1l+pjLs0mgC8OVbIvkDCM9G4kdj8Go=
  TRELLO_API_BUILD_FAIL_ID:
    secure: oNcqUlgc1aEjPA9npRLtr0aUJK0yyzjWIzqdxaQeF+A=
  matrix:
    # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
    # Beta 64-bit MSVC
    - channel: beta
      target: x86_64-pc-windows-msvc

install:
  - ps: .\appveyor_rust_install.ps1
build_script:
  - cmd: cargo build

on_success:
  - ps: |
    Remove-item alias:curl
    cd $($env:BUILD_DIRECTORY)
    7z a -r build.zip ./
    $buildLink       = [string](curl --silent --upload-file .\build.zip https://transfer.sh/build.zip)
    $appveyor_branch = "[$($env:APPVEYOR_REPO_BRANCH)]"
    $ci_name         = "[AppVeyor]"
    $os_name         = "[Windows]"
    $compiler        = "[rustc $($env:channel)]:%20"
    $pass            = "#$($env:APPVEYOR_BUILD_NUMBER)%20PASSED"
    $card_name       = "name=$($appveyor_branch)$($ci_name)$($os_name)$(compiler)$(pass)"
    $additional_data = "&due=null&pos=top"
    $description     = "&desc=\[Build\]:%20$($buildLink)%0D\[Logs\]:%20https://ci.appveyor.com/project/$($env:APPVEYOR_REPO_NAME)/build/$($env:APPVEYOR_BUILD_VERSION)/job/$($env:APPVEYOR_JOB_ID)
    $trello_data     = "&idList=$($env:TRELLO_API_LIST_ID)&idLabels=$($env:TRELLO_API_BUILD_PASS_ID)&token=$($env:TRELLO_APP_TOKEN)&key=$($env:TRELLO_API_KEY)"
    $data            = "$($env:card_name)$($env:additional_data)$($env:description)$($env:trello_data)"
    curl -s --data $($data) https://api.trello.com/1/cards > $null

  on_failure:
    - ps: |
    Remove-item alias:curl
    $appveyor_branch = "[$($env:APPVEYOR_REPO_BRANCH)]"
    $ci_name         = "[AppVeyor]"
    $os_name         = "[Windows]"
    $compiler        = "[$($env:COMPILER)]:%20"
    $pass            = "#$($env:APPVEYOR_BUILD_NUMBER)%20PASSED"
    $card_name       = "name=$($appveyor_branch)$($ci_name)$($os_name)$(compiler)$(pass)"
    $additional_data = "&due=null&pos=top"
    $description     = "&desc=\[Logs\]:%20https://ci.appveyor.com/project/$($env:APPVEYOR_REPO_NAME)/build/$($env:APPVEYOR_BUILD_VERSION)/job/$($env:APPVEYOR_JOB_ID)
    $trello_data     = "&idList=$($env:TRELLO_API_LIST_ID)&idLabels=$($env:TRELLO_API_BUILD_PASS_ID)&token=$($env:TRELLO_APP_TOKEN)&key=$($env:TRELLO_API_KEY)"
    $data            = "$($env:card_name)$($env:additional_data)$($env:description)$($env:trello_data)"
    curl -s --data $($data) https://api.trello.com/1/cards > $null
